ASP.NET-Restaurang/ViewComponents/VarorCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Restaurang.ViewComponents
{
    public class VarorCountViewComponent : ViewComponent
    {
        private readonly IVarorData varorData;

        public VarorCountViewComponent(IVarorData varorData)
        {
            this.varorData = varorData;
        }

        public IViewComponentResult Invoke()
        {
            var count = varorData.GetCountofVaror();
            return View(count);
          
        }
    }
}

ASP.NET-Restaurang/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Inköpslistan.nu</title>
    <link rel="icon" href="~/banan.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/53c6caddf7.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-toggleable-sm bg-primary navbar-dark border-bottom box-shadow mb-3 sticky-top">
             <div class="container font-weight-bold bg-primary">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Inköpslistan.nu</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/VarorModels/">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/VarorModels/List">Min Inköpslista</a>
                    </ul>
                </div>
            </div>
        </nav>

    <div class="container">
        @RenderBody()
        <hr />

        <footer>
            <vc:varor-count></vc:varor-count>
            @RenderSection("footer", required: false)
            <p>&copy; 2019 - Inköpslistan.nu</p>
            @*<img src="~/ripstigen.jpg" width="60" />*@
        </footer>
    </div> 


        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("Scripts", required: false)
</body>
</html>